### PR TITLE
created data json file

### LINKED ISSUE #2: #1 create data structure and store in json file
1. think over what data structure will I need
2. come up with 5-sh todos, try to have with the same title
3. figure how to put them into a `.json` file
4. think over on a proper location of data json file
5. store the file

### PR DESCRIPTION
**Pull request by JauniusZ**

### CODE REVIEW

**Review by arturasmckwcz — COMMENTED** [review]
the location of this file is the project root, right? why did you choose that?

**Comment by JauniusZ** [comment]
Because I thought it will be easy and convenient to access it there.

**Comment by arturasmckwcz** [comment]
> Because I thought it will be easy and convenient to access it there.

Okay that makes sense of course.
For now the project is going to comprise 4 files only, so there's no need to build a complex structure.

**Review by arturasmckwcz — APPROVED** [review]
well done!

**Pull request merged**
